version: "3"
services:
  mysql:
    container_name: mysql
    restart: always
    build: ./services/mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./services/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./services/mysql/mysqldump.cnf:/etc/mysql/conf.d/mysqldump.cnf
      - ./services/mysql/mysqldump.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_USER: laravel
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
  redis:
    container_name: redis
    restart: always
    build: ./services/redis
  php:
    container_name: php
    restart: always
    build: ./services/php
    volumes:
      - ./src/:/var/www/html
      - ./data/storage:/var/www/html/storage
    environment:
      PHP_IDE_CONFIG: "serverName=laravel-docker"
      APP_REPOSITORY: "laravel/laravel"
  nginx:
    container_name: nginx
    restart: always
    build: ./services/nginx
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html
      - ./services/nginx/sites:/etc/nginx/conf.d
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf