version: "3"
services:
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "8080:80"
    expose:
      - "9000"
    volumes:
      - ./src/:/var/www/html/
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./services/php/
    container_name: php
    volumes:
      - ./src:/var/www/html/
    environment:
      PHP_IDE_CONFIG: "serverName=laravel-docker"
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    environment:
      MYSQL_DATABASE: forge
      MYSQL_ROOT_PASSWORD: forge
    ports:
      - "3307:3306"